/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class Adddeliveryperson extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Adddeliveryperson.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public Adddeliveryperson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Staftname = new javax.swing.JTextField();
        Vechiletype = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Shift = new javax.swing.JTextField();
        addimage = new javax.swing.JLabel();
        brackgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Satf_name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 250, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Phone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 320, 50, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 380, 50, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 450, 80, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Shift");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 510, 40, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Vechile_type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 570, 110, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Add Delivery Person");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 90, 480, 80);

        Logout.setBackground(new java.awt.Color(0, 51, 255));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Log out");
        getContentPane().add(Logout);
        Logout.setBounds(1140, 20, 100, 23);

        Add.setBackground(new java.awt.Color(255, 51, 51));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(this::AddActionPerformed);
        getContentPane().add(Add);
        Add.setBounds(610, 630, 90, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Shift");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(460, 510, 40, 22);

        Staftname.setBackground(new java.awt.Color(204, 204, 204));
        Staftname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Staftname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Staftname);
        Staftname.setBounds(530, 250, 290, 40);

        Vechiletype.setBackground(new java.awt.Color(204, 204, 204));
        Vechiletype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Vechiletype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Vechiletype.addActionListener(this::VechiletypeActionPerformed);
        getContentPane().add(Vechiletype);
        Vechiletype.setBounds(530, 560, 290, 40);

        Phone.setBackground(new java.awt.Color(204, 204, 204));
        Phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Phone);
        Phone.setBounds(530, 310, 290, 40);

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Email);
        Email.setBounds(530, 370, 290, 40);

        Password.setBackground(new java.awt.Color(204, 204, 204));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Password);
        Password.setBounds(530, 440, 290, 40);

        Shift.setBackground(new java.awt.Color(204, 204, 204));
        Shift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Shift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Shift.addActionListener(this::ShiftActionPerformed);
        getContentPane().add(Shift);
        Shift.setBounds(530, 500, 290, 40);

        addimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addimage.setText("jLabel3");
        addimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(addimage);
        addimage.setBounds(300, 210, 720, 490);

        brackgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminImage.jpg"))); // NOI18N
        brackgroundimage.setText("jLabel1");
        brackgroundimage.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(brackgroundimage);
        brackgroundimage.setBounds(0, 0, 1270, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VechiletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VechiletypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VechiletypeActionPerformed

    private void ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShiftActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Adddeliveryperson().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Shift;
    private javax.swing.JTextField Staftname;
    private javax.swing.JTextField Vechiletype;
    private javax.swing.JLabel addimage;
    private javax.swing.JLabel brackgroundimage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
