/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JTable;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class DeliveryDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeliveryDash.class.getName());

    /**
     * Creates new form DeliveryDash
     */
    public DeliveryDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        deliveredButton = new javax.swing.JButton();
        enRouteButton = new javax.swing.JButton();
        pickUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order_id", "Customer Name", "Address", "Phone Number", "Delivery Time", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 210, 890, 430);

        backButton.setBackground(new java.awt.Color(255, 0, 51));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Log Out");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        getContentPane().add(backButton);
        backButton.setBounds(30, 20, 130, 30);

        deliveredButton.setBackground(new java.awt.Color(153, 204, 0));
        deliveredButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deliveredButton.setForeground(new java.awt.Color(255, 255, 255));
        deliveredButton.setText("Delivered");
        getContentPane().add(deliveredButton);
        deliveredButton.setBounds(1080, 710, 100, 40);

        enRouteButton.setBackground(new java.awt.Color(0, 0, 0));
        enRouteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enRouteButton.setForeground(new java.awt.Color(255, 255, 255));
        enRouteButton.setText("Ent-Route");
        getContentPane().add(enRouteButton);
        enRouteButton.setBounds(920, 710, 120, 40);

        pickUpButton.setBackground(new java.awt.Color(0, 51, 255));
        pickUpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pickUpButton.setForeground(new java.awt.Color(255, 255, 255));
        pickUpButton.setText("Picked Up");
        getContentPane().add(pickUpButton);
        pickUpButton.setBounds(760, 710, 120, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Delivery Dashboard ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(480, 120, 520, 50);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kitchen.jpg"))); // NOI18N
        backgroundImage.setText("jLabel1");
        backgroundImage.setPreferredSize(new java.awt.Dimension(1273, 789));
        backgroundImage.setRequestFocusEnabled(false);
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1302, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeliveryDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JButton deliveredButton;
    private javax.swing.JButton enRouteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pickUpButton;
    // End of variables declaration//GEN-END:variables

public JTable getTable() {
    return jTable1;
}

public void pickedUpListener(ActionListener l) {
    pickUpButton.addActionListener(l);
}

public void enRouteListener(ActionListener l) {
    enRouteButton.addActionListener(l);
}

public void deliveredListener(ActionListener l) {
    deliveredButton.addActionListener(l);
}
public void backBtnListener(ActionListener l) {
    backButton.addActionListener(l);
}

    
}
