/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class DescriptionDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescriptionDash.class.getName());

    /**
     * Creates new form Description
     */
    public DescriptionDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addTocardButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        imagePizaa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Location");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(760, 390, 80, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 270, 90, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 330, 80, 20);

        details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/details.png"))); // NOI18N
        details.setText("Pizza");
        getContentPane().add(details);
        details.setBounds(50, 430, 490, 340);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pizza.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 550, 350);

        placeOrderButton.setBackground(new java.awt.Color(255, 0, 51));
        placeOrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        placeOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(this::placeOrderButtonActionPerformed);
        getContentPane().add(placeOrderButton);
        placeOrderButton.setBounds(840, 460, 110, 23);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(backButton);
        backButton.setBounds(9, 10, 110, 30);

        addTocardButton.setBackground(new java.awt.Color(0, 51, 255));
        addTocardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addTocardButton.setForeground(new java.awt.Color(255, 255, 255));
        addTocardButton.setText("Add to card");
        addTocardButton.addActionListener(this::addTocardButtonActionPerformed);
        getContentPane().add(addTocardButton);
        addTocardButton.setBounds(970, 460, 120, 30);

        userName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(userName);
        userName.setBounds(850, 260, 230, 40);

        location.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        location.setBorder(new javax.swing.border.MatteBorder(null));
        location.addActionListener(this::locationActionPerformed);
        getContentPane().add(location);
        location.setBounds(850, 320, 230, 40);

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        phone.addActionListener(this::phoneActionPerformed);
        getContentPane().add(phone);
        phone.setBounds(850, 380, 230, 40);

        imagePizaa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description.jpeg"))); // NOI18N
        imagePizaa.setText("jLabel1");
        imagePizaa.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(imagePizaa);
        imagePizaa.setBounds(0, 0, 1273, 795);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addTocardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTocardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTocardButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DescriptionDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTocardButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel details;
    private javax.swing.JLabel imagePizaa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField location;
    private javax.swing.JTextField phone;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
