/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CartManager;
import controller.MainPageController;
import dao.CustomerDao;
import dao.KitchenDao;
import dao.OrderDao;
import dao.UserDao;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.CartItem;
import model.Item;
import model.Users;
import utils.Session;
import utils.UserSession;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class DescriptionDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DescriptionDash.class.getName());

    /**
     * Creates new form Description
     */
    public DescriptionDash() {
        initComponents();
    }
    
//    public DescriptionDash(Item item) {
//        initComponents();
//    }
//    
    private Item product;
    private KitchenDao kitchendao;
    
    
    public DescriptionDash(Item product) {
        this.product = product;
        initComponents();
        loadProductDetails();
        loadUserDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        imagePizaa = new javax.swing.JLabel();
        placeOrderButton = new javax.swing.JButton();
        addTocardButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        backLabel = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(740, 390, 80, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 270, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Location");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 330, 80, 20);

        details.setFont(new java.awt.Font("Helvetica Neue", 2, 36)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 255));
        details.setText("Pizza");
        getContentPane().add(details);
        details.setBounds(60, 410, 490, 220);

        imagePizaa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(imagePizaa);
        imagePizaa.setBounds(60, 60, 550, 350);

        placeOrderButton.setBackground(new java.awt.Color(255, 0, 51));
        placeOrderButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        placeOrderButton.setForeground(new java.awt.Color(255, 255, 255));
        placeOrderButton.setText("Place Order");
        placeOrderButton.addActionListener(this::placeOrderButtonActionPerformed);
        getContentPane().add(placeOrderButton);
        placeOrderButton.setBounds(810, 460, 130, 30);

        addTocardButton.setBackground(new java.awt.Color(0, 51, 255));
        addTocardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addTocardButton.setForeground(new java.awt.Color(255, 255, 255));
        addTocardButton.setText("Add to card");
        addTocardButton.addActionListener(this::addTocardButtonActionPerformed);
        getContentPane().add(addTocardButton);
        addTocardButton.setBounds(970, 460, 120, 30);

        userName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(userName);
        userName.setBounds(850, 260, 230, 40);

        location.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        location.setBorder(new javax.swing.border.MatteBorder(null));
        location.addActionListener(this::locationActionPerformed);
        getContentPane().add(location);
        location.setBounds(850, 320, 230, 40);

        phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        phone.addActionListener(this::phoneActionPerformed);
        getContentPane().add(phone);
        phone.setBounds(850, 380, 230, 40);

        backLabel.setFont(new java.awt.Font("Kaiti SC", 1, 36)); // NOI18N
        backLabel.setText(" < Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        getContentPane().add(backLabel);
        backLabel.setBounds(1020, 20, 140, 50);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description1.jpeg"))); // NOI18N
        backgroundImage.setText("jLabel1");
        backgroundImage.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(backgroundImage);
        backgroundImage.setBounds(0, 0, 1273, 795);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void addTocardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTocardButtonActionPerformed
        // TODO add your handling code here:
        //CartManager.getInstance().addItem(product);
        CartItem cartItem = new CartItem(
            product.getItem_id(),
            product.getItemName(),
            product.getPrice(),
            product.getImagePath()
        );

    CartManager.getInstance().addItem(cartItem);

        JOptionPane.showMessageDialog(this, "Added to Cart 🛒");
        MainPage mp = new MainPage();
        mp.updateHeader();



    }//GEN-LAST:event_addTocardButtonActionPerformed

    private void placeOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderButtonActionPerformed
        // TODO add your handling code here:
        if (location.getText().trim().isEmpty() || phone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter phone and location");
            return;
        }

        Users user = UserSession.getCurrentUser();
        long phoneNumber = Long.parseLong(phone.getText());
        String address = location.getText();

        // 1️⃣ Update phone in users table
        UserDao userDao = new UserDao();
        userDao.updatePhone(user.getUser_id(), phoneNumber);

        // 2️⃣ Create or update customer
        CustomerDao customerDao = new CustomerDao();
        int customerId = customerDao.getOrCreateCustomer(user.getUser_id(), address);

        if (customerId == -1) {
            JOptionPane.showMessageDialog(this, "Customer creation failed");
            return;
        }

        // 3️⃣ Create order
        OrderDao orderDao = new OrderDao();
        //int orderId = orderDao.createOrder(customerId, product.getPrice());
        
                 //1. Create order
        int orderId = orderDao.createOrder(customerId, product.getPrice());

        // 2. For each cart item → insert into kitchen
        for (CartItem item : CartManager.getInstance().getItems()) {
            kitchendao.addKitchenOrder(orderId, item.getItemId());
        }

        // 3. Update order status
        orderDao.updateOrderStatus(orderId, "PREPARING");
        

        // 4️⃣ Send to kitchen
        KitchenDao kitchenDao = new KitchenDao();
        kitchenDao.addKitchenOrder(orderId, product.getItem_id());

        JOptionPane.showMessageDialog(this, "Order placed successfully 🍕");
        this.dispose();
    }//GEN-LAST:event_placeOrderButtonActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        MainPage mp = new MainPage();
        MainPageController controller = new MainPageController(mp);
        controller.open();
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DescriptionDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTocardButton;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel details;
    private javax.swing.JLabel imagePizaa;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField location;
    private javax.swing.JTextField phone;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

public void backButtonListener(ActionListener l){
//    backButton.addActionListener(l);
}


private void loadProductDetails() {
    if (product == null) return;

    details.setText(
        "<html>"
        + "<h2>" + product.getItemName() + "</h2>"
        + "<p>Category: " + product.getCategory() + "</p>"
        + "<p>Price: Rs. " + product.getPrice() + "</p>"
        + "</html>"
    );

    ImageIcon icon = new ImageIcon(product.getImagePath());
    Image img = icon.getImage().getScaledInstance(backgroundImage.getWidth(),
            backgroundImage.getHeight(),
            Image.SCALE_SMOOTH
    );
    imagePizaa.setIcon(new ImageIcon(img));
}




private void loadUserDetails() {
    Users user = UserSession.getCurrentUser();

    if (user != null) {
        userName.setText(user.getUsername());
        phone.setText(String.valueOf(user.getPhone()));
        userName.setEditable(false);
        phone.setEditable(true);
    }
}




}
