/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainPageController;
import dao.ItemDao;
import javax.swing.JOptionPane;
import model.Item;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class EditItemDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditItemDashboard.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private ItemDao itemDao = new ItemDao();
    private Item item;
    public EditItemDashboard() {
        initComponents();
    }
    public EditItemDashboard(Item item) {
        this.item = item;
        initComponents();
        loadItemDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtItemPrice = new javax.swing.JTextField();
        txtImageUrl = new javax.swing.JTextField();
        comboAvailability = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        addimage = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        brackgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Item Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 250, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 310, 110, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 380, 140, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Image");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 450, 140, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Availability");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(360, 510, 130, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Edit Items");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 80, 480, 80);

        btnSave.setBackground(new java.awt.Color(0, 153, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        getContentPane().add(btnSave);
        btnSave.setBounds(570, 620, 90, 40);

        txtItemName.setBackground(new java.awt.Color(204, 204, 204));
        txtItemName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItemName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtItemName);
        txtItemName.setBounds(530, 250, 290, 40);

        txtCategory.setBackground(new java.awt.Color(204, 204, 204));
        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCategory);
        txtCategory.setBounds(530, 310, 290, 40);

        txtItemPrice.setBackground(new java.awt.Color(204, 204, 204));
        txtItemPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtItemPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtItemPrice);
        txtItemPrice.setBounds(530, 370, 290, 40);

        txtImageUrl.setBackground(new java.awt.Color(204, 204, 204));
        txtImageUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtImageUrl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtImageUrl);
        txtImageUrl.setBounds(530, 440, 290, 40);

        comboAvailability.setBackground(new java.awt.Color(204, 204, 204));
        comboAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "NOT AVAILABLE" }));
        getContentPane().add(comboAvailability);
        comboAvailability.setBounds(530, 500, 290, 40);

        btnCancel.setBackground(new java.awt.Color(255, 51, 51));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(680, 620, 100, 40);

        addimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addimage.setText("jLabel3");
        addimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(addimage);
        addimage.setBounds(300, 210, 720, 490);

        backLabel.setFont(new java.awt.Font("Kaiti SC", 1, 36)); // NOI18N
        backLabel.setText(" < Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        getContentPane().add(backLabel);
        backLabel.setBounds(20, 40, 140, 50);

        brackgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminImage.jpg"))); // NOI18N
        brackgroundimage.setText("jLabel1");
        brackgroundimage.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(brackgroundimage);
        brackgroundimage.setBounds(0, 0, 1270, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        updateItem();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditItemDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addimage;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel brackgroundimage;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboAvailability;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtImageUrl;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    // End of variables declaration//GEN-END:variables

    public void updateItem() {
        try {
            item.setItemName(txtItemName.getText());
            item.setCategory(txtCategory.getText());
            item.setPrice(Double.parseDouble(txtItemPrice.getText()));
            item.setImagePath(txtImageUrl.getText());
            item.setAvailability(comboAvailability.getSelectedItem().toString());

            itemDao.updateItem(item);

            JOptionPane.showMessageDialog(this, "Item Updated Successfully");
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid Data");
            ex.printStackTrace();
        }
    }

    
    private void loadItemDetails(){
        if (item!= null) {
            txtItemName.setText(item.getItemName());
            txtCategory.setText(item.getCategory());
            //txtItemPrice.setText(item.getPrice());
            txtImageUrl.setText(item.getImagePath());
            comboAvailability.setSelectedIndex(WIDTH);
        }
    }
    
    
}
