/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainPageController;
import dao.UserDao;
import javax.swing.JOptionPane;
import model.Users;
import utils.PasswordUtil;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class Edituserinfo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Edituserinfo.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private Users user;
    
    public Edituserinfo() {
        initComponents();
    }
    
    public Edituserinfo(Users user) {
        this.user =user;
        initComponents();
        loadUserDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Password = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Edit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        ph = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        brackgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1273, 789));
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        Password.setBackground(new java.awt.Color(204, 204, 204));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Password.addActionListener(this::PasswordActionPerformed);
        getContentPane().add(Password);
        Password.setBounds(550, 410, 260, 40);

        Username.setBackground(new java.awt.Color(204, 204, 204));
        Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Username.addActionListener(this::UsernameActionPerformed);
        getContentPane().add(Username);
        Username.setBounds(550, 280, 260, 40);

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Email);
        Email.setBounds(550, 350, 260, 40);

        Edit.setBackground(new java.awt.Color(0, 153, 255));
        Edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.addActionListener(this::EditActionPerformed);
        getContentPane().add(Edit);
        Edit.setBounds(520, 580, 90, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 420, 90, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Edit User Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 80, 560, 58);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 290, 100, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(470, 360, 60, 22);

        cancelBtn.setBackground(new java.awt.Color(255, 0, 51));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(650, 580, 120, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone no.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 480, 90, 22);

        phoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        phoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phoneNumber.addActionListener(this::phoneNumberActionPerformed);
        getContentPane().add(phoneNumber);
        phoneNumber.setBounds(550, 470, 260, 40);

        ph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        ph.setText("jLabel3");
        ph.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(ph);
        ph.setBounds(300, 180, 710, 480);

        backLabel.setFont(new java.awt.Font("Kaiti SC", 1, 36)); // NOI18N
        backLabel.setText(" < Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        getContentPane().add(backLabel);
        backLabel.setBounds(80, 30, 140, 50);

        brackgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminImage.jpg"))); // NOI18N
        brackgroundimage.setText("jLabel1");
        brackgroundimage.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(brackgroundimage);
        brackgroundimage.setBounds(0, 0, 1270, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        updateUser();
        
    }//GEN-LAST:event_EditActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Edituserinfo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel brackgroundimage;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel ph;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables

    public void loadData() {
        Username.setText(user.getUsername());
        Email.setText(user.getEmail());
        Password.setText(user.getPassword());
        
    }

    public void updateUser() {
        user.setUsername(Username.getText());
        user.setEmail(Email.getText());

        String rawPassword = Password.getText();
        user.setPassword(PasswordUtil.hashPassword(rawPassword));

        long phone = Long.parseLong(phoneNumber.getText().trim());
        user.setPhone(phone);

        user.setRole("CUSTOMER");

        UserDao dao = new UserDao();
        boolean success = dao.updateUser(user);

        if (success) {
            JOptionPane.showMessageDialog(this, "User updated successfully");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update user");
        }
    }


    private void loadUserDetails() {
        if (user != null) {
            Username.setText(user.getUsername());
            Email.setText(user.getEmail());
            Password.setText(""); // NEVER show password
            phoneNumber.setText(String.valueOf(user.getPhone()));
        }
    }

    

}
