/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainPageController;
import dao.DeliveryDao;
import javax.swing.JOptionPane;
import model.DeliveryStaff;
import model.Users;
import utils.PasswordUtil;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class Editdeliveryperson extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editdeliveryperson.class.getName());

    /**
     * Creates new form NewJFrame
     */
    
    private DeliveryDao dao; 
    private DeliveryStaff staff;
    private Users user;
    private Runnable onUpdate;

    public Editdeliveryperson() {
        initComponents();
    }
    
    public Editdeliveryperson(DeliveryStaff staff, Runnable onUpdate) {
        this.staff = staff;
        this.dao = new DeliveryDao();
        this.user = dao.getUserById(staff.getUser_id()); // ✅ LOAD USER
        initComponents();
        loadPersonDetails();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Staftname = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Shift = new javax.swing.JTextField();
        Vechiletype = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        addimage = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        brackgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Edit Delivery Person Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 90, 811, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Satf_name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 250, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 380, 80, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 450, 100, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Shift");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 510, 40, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Vechile_type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 570, 110, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Phone");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 320, 80, 22);

        Edit.setBackground(new java.awt.Color(255, 51, 51));
        Edit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.addActionListener(this::EditActionPerformed);
        getContentPane().add(Edit);
        Edit.setBounds(540, 640, 90, 40);

        Staftname.setBackground(new java.awt.Color(204, 204, 204));
        Staftname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Staftname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Staftname);
        Staftname.setBounds(530, 250, 290, 40);

        Phone.setBackground(new java.awt.Color(204, 204, 204));
        Phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Phone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Phone);
        Phone.setBounds(530, 310, 290, 40);

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Email);
        Email.setBounds(530, 370, 290, 40);

        Password.setBackground(new java.awt.Color(204, 204, 204));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Password);
        Password.setBounds(530, 440, 290, 40);

        Shift.setBackground(new java.awt.Color(204, 204, 204));
        Shift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Shift.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Shift.addActionListener(this::ShiftActionPerformed);
        getContentPane().add(Shift);
        Shift.setBounds(530, 500, 290, 40);

        Vechiletype.setBackground(new java.awt.Color(204, 204, 204));
        Vechiletype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Vechiletype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Vechiletype.addActionListener(this::VechiletypeActionPerformed);
        getContentPane().add(Vechiletype);
        Vechiletype.setBounds(530, 560, 290, 40);

        cancelBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(680, 640, 100, 40);

        addimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addimage.setText("jLabel3");
        addimage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(addimage);
        addimage.setBounds(300, 210, 720, 490);

        backLabel.setFont(new java.awt.Font("Kaiti SC", 1, 36)); // NOI18N
        backLabel.setText(" < Back");
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        getContentPane().add(backLabel);
        backLabel.setBounds(60, 40, 140, 50);

        brackgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adminImage.jpg"))); // NOI18N
        brackgroundimage.setText("jLabel1");
        brackgroundimage.setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().add(brackgroundimage);
        brackgroundimage.setBounds(0, 0, 1270, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VechiletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VechiletypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VechiletypeActionPerformed

    private void ShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShiftActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
       update();
    }//GEN-LAST:event_EditActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_backLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editdeliveryperson().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Shift;
    private javax.swing.JTextField Staftname;
    private javax.swing.JTextField Vechiletype;
    private javax.swing.JLabel addimage;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel brackgroundimage;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    
    private void update() {

        if (staff == null || staff.getDeliveryStaff_id() <= 0) {
            JOptionPane.showMessageDialog(this, "Invalid staff ID");
            return;
        }

        // ---------- PHONE ----------
        String phoneText = Phone.getText().trim();
        if (phoneText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone cannot be empty");
            return;
        }

        long phone;
        try {
            phone = Long.parseLong(phoneText);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid phone number");
            return;
        }

        // ---------- PASSWORD ----------
        String rawPassword = Password.getText().trim();
        if (rawPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty");
            return;
        }

        String hashedPassword = PasswordUtil.hashPassword(rawPassword);

        boolean updated = dao.updateDeliveryStaff(
            staff.getDeliveryStaff_id(),
            Vechiletype.getText().trim(),
            Shift.getText().trim(),
            Email.getText().trim(),
            Staftname.getText().trim(),
            phone,                 //  FIX: use value from text field
            hashedPassword
        );

        if (updated) {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Update failed");
        }
    }


    private void loadPersonDetails() {
        if (staff != null) {
            Staftname.setText(staff.getName());
            Phone.setText(String.valueOf(staff.getPhone()));
            Shift.setText(staff.getShift());
            Vechiletype.setText(staff.getVehicleType());
        }

        if (user != null) {
            Email.setText(user.getEmail());

        }
    }
    
}
