/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class kitchenDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kitchenDash.class.getName());

    /**
     * Creates new form demo
     */
    public kitchenDash() {
        initComponents();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KitchenIcon = new javax.swing.JLabel();
        Markasready = new javax.swing.JButton();
        Startcooking = new javax.swing.JButton();
        KitchenPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        KitchenIcon.setBackground(new java.awt.Color(255, 255, 255));
        KitchenIcon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        KitchenIcon.setForeground(new java.awt.Color(0, 0, 0));
        KitchenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/k-icon.png"))); // NOI18N
        KitchenIcon.setToolTipText("");
        getContentPane().add(KitchenIcon);
        KitchenIcon.setBounds(420, 60, 360, 100);

        Markasready.setBackground(new java.awt.Color(255, 0, 51));
        Markasready.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Markasready.setForeground(new java.awt.Color(255, 255, 255));
        Markasready.setText("Mark as ready");
        getContentPane().add(Markasready);
        Markasready.setBounds(900, 630, 170, 50);

        Startcooking.setBackground(new java.awt.Color(51, 51, 255));
        Startcooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Startcooking.setForeground(new java.awt.Color(255, 255, 255));
        Startcooking.setText("Start cooking");
        getContentPane().add(Startcooking);
        Startcooking.setBounds(710, 630, 160, 50);

        KitchenPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        KitchenPane.setForeground(new java.awt.Color(255, 255, 255));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        table.setForeground(new java.awt.Color(0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order_id", "Status", "Customer", "Items", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        KitchenPane.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMaxWidth(122);
        }

        getContentPane().add(KitchenPane);
        KitchenPane.setBounds(180, 210, 850, 370);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kitchen.jpg"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        getContentPane().add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 1287, 789);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kitchenDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel KitchenIcon;
    private javax.swing.JScrollPane KitchenPane;
    private javax.swing.JButton Markasready;
    private javax.swing.JButton Startcooking;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

   
}
