/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.KitchenController;
import controller.LoginController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Kitchen;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class kitchenDash extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(kitchenDash.class.getName());

    /**
     * Creates new form demo
     */
    private KitchenController kitchenController;
    
    public kitchenDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KitchenIcon = new javax.swing.JLabel();
        Markasready = new javax.swing.JButton();
        Startcooking = new javax.swing.JButton();
        KitchenPane = new javax.swing.JScrollPane();
        kitchenTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1273, 789));
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        KitchenIcon.setBackground(new java.awt.Color(255, 255, 255));
        KitchenIcon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        KitchenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/k-icon.png"))); // NOI18N
        KitchenIcon.setToolTipText("");
        getContentPane().add(KitchenIcon);
        KitchenIcon.setBounds(420, 60, 360, 100);

        Markasready.setBackground(new java.awt.Color(255, 0, 51));
        Markasready.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Markasready.setForeground(new java.awt.Color(255, 255, 255));
        Markasready.setText("Mark as ready");
        Markasready.addActionListener(this::MarkasreadyActionPerformed);
        getContentPane().add(Markasready);
        Markasready.setBounds(960, 700, 170, 50);

        Startcooking.setBackground(new java.awt.Color(51, 51, 255));
        Startcooking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Startcooking.setForeground(new java.awt.Color(255, 255, 255));
        Startcooking.setText("Start cooking");
        Startcooking.addActionListener(this::StartcookingActionPerformed);
        getContentPane().add(Startcooking);
        Startcooking.setBounds(760, 700, 160, 50);

        KitchenPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        KitchenPane.setForeground(new java.awt.Color(255, 255, 255));

        kitchenTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        kitchenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order_id", "Status", "Customer", "Items", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        KitchenPane.setViewportView(kitchenTable);
        if (kitchenTable.getColumnModel().getColumnCount() > 0) {
            kitchenTable.getColumnModel().getColumn(0).setMaxWidth(122);
        }

        getContentPane().add(KitchenPane);
        KitchenPane.setBounds(180, 210, 950, 404);

        backButton.setBackground(new java.awt.Color(255, 0, 51));
        backButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Log Out");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        backButton.addActionListener(this::backButtonActionPerformed);
        getContentPane().add(backButton);
        backButton.setBounds(30, 20, 130, 30);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kitchen.jpg"))); // NOI18N
        BackgroundImage.setText("jLabel1");
        getContentPane().add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 1287, 789);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartcookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartcookingActionPerformed
       
        }//GEN-LAST:event_StartcookingActionPerformed

    private void MarkasreadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkasreadyActionPerformed
        
    }//GEN-LAST:event_MarkasreadyActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new kitchenDash().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel KitchenIcon;
    private javax.swing.JScrollPane KitchenPane;
    private javax.swing.JButton Markasready;
    private javax.swing.JButton Startcooking;
    private javax.swing.JButton backButton;
    private javax.swing.JTable kitchenTable;
    // End of variables declaration//GEN-END:variables
 
    public void populateTable(List<Kitchen> orders) {
        DefaultTableModel model = (DefaultTableModel) kitchenTable.getModel();
        model.setRowCount(0);

        for (Kitchen k : orders) {
            model.addRow(new Object[]{
                k.getOrder_id(),
                k.getCookingStatus(),
                k.getCustomer_id(),
                k.getItemName(),
                k.getOrderTime()
            });


        }
    }
    
    public JTable getKitchenTable() {
        return kitchenTable;
    }

    public void startCookingListener(ActionListener l) {
        Startcooking.addActionListener(l);
    }

    public void markReadyListener(ActionListener l) {
        Markasready.addActionListener(l);
    }

}
