/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ForgetPassController;
import controller.LoginController;
import controller.UserController;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        forgetPasswordLink = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginHere = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        username = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1723, 789));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1723, 789));
        jPanel1.setLayout(null);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpg"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 435, 790);

        login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        login.setText("Login Page");
        jPanel1.add(login);
        login.setBounds(830, 150, 150, 30);

        loginButton.setBackground(new java.awt.Color(255, 0, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("login");
        loginButton.addActionListener(this::loginButtonActionPerformed);
        jPanel1.add(loginButton);
        loginButton.setBounds(850, 390, 79, 23);

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Enter your E-mail");
        email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(this::emailActionPerformed);
        jPanel1.add(email);
        email.setBounds(750, 250, 290, 40);

        forgetPasswordLink.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        forgetPasswordLink.setForeground(new java.awt.Color(255, 51, 51));
        forgetPasswordLink.setText("forget password ?");
        forgetPasswordLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordLinkMouseClicked(evt);
            }
        });
        jPanel1.add(forgetPasswordLink);
        forgetPasswordLink.setBounds(830, 450, 140, 17);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Don't have an account?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(760, 480, 170, 17);

        loginHere.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginHere.setForeground(new java.awt.Color(51, 51, 255));
        loginHere.setText("signup Here");
        loginHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginHereMouseClicked(evt);
            }
        });
        jPanel1.add(loginHere);
        loginHere.setBounds(920, 480, 90, 17);

        role.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "CUSTOMER", "KITCHEN", "DELIVERY" }));
        role.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        role.addActionListener(this::roleActionPerformed);
        jPanel1.add(role);
        role.setBounds(1150, 10, 130, 30);

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setText("E-mail");
        jPanel1.add(username);
        username.setBounds(650, 250, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(650, 310, 90, 40);

        password.setText("12345678");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(this::passwordActionPerformed);
        jPanel1.add(password);
        password.setBounds(750, 310, 290, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1287, 789);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void loginHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginHereMouseClicked
        // TODO add your handling code here:
        SignUp userview = new SignUp();
        UserController controller = new UserController(userview);
        controller.open();
    }//GEN-LAST:event_loginHereMouseClicked

    private void forgetPasswordLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordLinkMouseClicked
        // TODO add your handling code here:
        forgetpass fgp = new forgetpass();
        ForgetPassController controller = new ForgetPassController(fgp);
        controller.open();
    }//GEN-LAST:event_forgetPasswordLinkMouseClicked

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Enter your E-mail")){
            email.setText("");
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            email.setText("Enter your E-mail");
        }
    }//GEN-LAST:event_emailFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("12345678")){
            email.setText("");
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            email.setText("12345678");
        }
    }//GEN-LAST:event_passwordFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        login loginView = new login();
        LoginController controller = new LoginController(loginView);
        controller.open();
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel forgetPasswordLink;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginHere;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getEmail(){
        return email;
    }
    public javax.swing.JTextField getPassword(){
        return password;
    }
    
    public javax.swing.JComboBox getRole(){
        return role;
    }
    
    public void AddLoginListener(ActionListener listener){
        loginButton.addActionListener(listener);
    }
    
    

}
