/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MainPageController;
import dao.ItemDao;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JPanel;
import model.Item;

/**
 *
 * @author Asus
 */
public class MainPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPage.class.getName());
    

    /**
     * Creates new form DashBoard
     */
  

    public MainPage() {
        initComponents();
        
    }

//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        Signup = new javax.swing.JButton();
        Cart = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        categoryCombo = new javax.swing.JComboBox<>();
        scrollPaneProducts = new javax.swing.JScrollPane();
        cardsPanel = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 39, 38));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(29, 29, 28));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo1.1.1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 80);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 210, 150, 50);

        jLabel27.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Cloud Kitchen");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 80, 110, 40);

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon1.1.1.png"))); // NOI18N
        jPanel1.add(searchBtn);
        searchBtn.setBounds(750, 30, 50, 40);

        searchField.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        searchField.setText("                                     Search");
        searchField.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.GRAY);
                g2.drawRoundRect(x, y, width - 1, height - 1, 20, 20);
            }
        });
        searchField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFieldFocusLost(evt);
            }
        });
        searchField.addActionListener(this::searchFieldActionPerformed);
        jPanel1.add(searchField);
        searchField.setBounds(340, 30, 460, 40);

        Signup.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        Signup.setText("Sign up");
        Signup.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.GRAY);
                g2.drawRoundRect(x, y, width - 1, height - 1, 20, 20);
            }
        });
        jPanel1.add(Signup);
        Signup.setBounds(1260, 20, 90, 40);

        Cart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cart.png"))); // NOI18N
        jPanel1.add(Cart);
        Cart.setBounds(1110, 30, 30, 30);

        Login.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        Login.setText("Login");
        Login.setBorder(new javax.swing.border.AbstractBorder() {
            @Override
            public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
                java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
                g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(java.awt.Color.GRAY);
                g2.drawRoundRect(x, y, width - 1, height - 1, 20, 20);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(1160, 20, 90, 40);

        categoryCombo.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        categoryCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categories", "Fast Food", "Pizza", "Snacks", "Main Course", "Beverage" }));
        jPanel1.add(categoryCombo);
        categoryCombo.setBounds(840, 32, 210, 40);

        scrollPaneProducts.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneProducts.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneProducts.setHorizontalScrollBar(null);

        cardsPanel.setBackground(new java.awt.Color(39, 39, 38));
        scrollPaneProducts.setViewportView(cardsPanel);

        jPanel1.add(scrollPaneProducts);
        scrollPaneProducts.setBounds(60, 280, 1330, 510);

        jScrollBar1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.add(jScrollBar1);
        jScrollBar1.setBounds(1380, 290, 10, 48);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusLost
        // TODO add your handling code here:
        if(searchField.getText().equals("")){
            searchField.setText("                                     Search");
        }
    }//GEN-LAST:event_searchFieldFocusLost

    private void searchFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFieldFocusGained
        // TODO add your handling code here:
        if(searchField.getText().equals("                                     Search")){
            searchField.setText("");
        }
    }//GEN-LAST:event_searchFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cart;
    private javax.swing.JButton Login;
    private javax.swing.JButton Signup;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JComboBox<String> categoryCombo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane scrollPaneProducts;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables

public JPanel getItemPanel(){
    return cardsPanel;
}

public void searchBtnListener(ActionListener listener){
    searchBtn.addActionListener(listener);
}

public void categoryComboListener(ActionListener listener){
    categoryCombo.addActionListener(listener);
}

public javax.swing.JTextField getSearchField(){
    return searchField;
}

public javax.swing.JComboBox<String> getCategoryCombo(){
    return categoryCombo;
}

//private void loadItems(java.util.List<Item> items) {
//    itemsContainer.removeAll();
//
//    for (Item item : items) {
//        itemsContainer.add(new ProductCardPanel(item));
//    }
//
//    itemsContainer.revalidate();
//    itemsContainer.repaint();
//}



}
