/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.OrderController;
import dao.DeliveryAssignmentDao;
import dao.DeliveryDao;
import dao.OrderDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DeliveryStaff;
import model.Order;
import tablemodel.OrderTableModel;

/**
 *
 * @author deepakshah
 */
public class OrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    
    private OrderController controller;
    public OrderPanel() {
        initComponents();
        
        OrderController controller = new OrderController(orderTable);
        controller.loadOrders();

        assignToKitchenbtn.addActionListener(e -> {
            controller.assignToKitchen(orderTable.getSelectedRow());
        });

        cancelOrderbtn.addActionListener(e -> {
            controller.cancelOrder(orderTable.getSelectedRow());
        });

        
    }

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        assignToKitchenbtn = new javax.swing.JButton();
        cancelOrderbtn = new javax.swing.JButton();
        assignDeliveryPerson = new javax.swing.JButton();

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order_id", "Customer_id", "Total Amount", "Order Time", "Order Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);

        assignToKitchenbtn.setBackground(new java.awt.Color(153, 204, 0));
        assignToKitchenbtn.setForeground(new java.awt.Color(255, 255, 255));
        assignToKitchenbtn.setText("Assign To Kitchen");
        assignToKitchenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToKitchenbtnActionPerformed(evt);
            }
        });

        cancelOrderbtn.setBackground(new java.awt.Color(255, 51, 0));
        cancelOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelOrderbtn.setText("Cancel Order");

        assignDeliveryPerson.setBackground(new java.awt.Color(51, 204, 255));
        assignDeliveryPerson.setForeground(new java.awt.Color(255, 255, 255));
        assignDeliveryPerson.setText("Assign DeliveryMan");
        assignDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDeliveryPersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assignToKitchenbtn)
                .addGap(28, 28, 28)
                .addComponent(assignDeliveryPerson)
                .addGap(31, 31, 31)
                .addComponent(cancelOrderbtn)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignDeliveryPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignToKitchenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToKitchenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToKitchenbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignToKitchenbtnActionPerformed

    private void assignDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDeliveryPersonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select an order first");
            return;
        }

        int orderId = (int) orderTable.getValueAt(selectedRow, 0);

        DeliveryDao staffDao = new DeliveryDao();
        List<DeliveryStaff> staffList = staffDao.getAllDeliveryStaff();

        JComboBox<DeliveryStaff> staffCombo = new JComboBox<>();
        for (DeliveryStaff d : staffList) {
            staffCombo.addItem(d);
        }

        int result = JOptionPane.showConfirmDialog(
                this,
                staffCombo,
                "Select Delivery Person",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (result == JOptionPane.OK_OPTION) {
            DeliveryStaff selected = (DeliveryStaff) staffCombo.getSelectedItem();

            DeliveryAssignmentDao assignDao = new DeliveryAssignmentDao();
            assignDao.assignOrderToDelivery(orderId, selected.getDeliveryStaff_id());
            assignDao.updateOrderStatus(orderId);

            JOptionPane.showMessageDialog(this, "Order assigned successfully 🚚");
            initOrderTable();
            //loadOrders(); // refresh table
            
        }
    }//GEN-LAST:event_assignDeliveryPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignDeliveryPerson;
    private javax.swing.JButton assignToKitchenbtn;
    private javax.swing.JButton cancelOrderbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables

    
    private OrderTableModel orderTableModel;

    private void initOrderTable() {
        orderTableModel = new OrderTableModel(new ArrayList<>());
        orderTable.setModel(orderTableModel);
        loadOrders();
    }

    private void loadOrders() {
        OrderDao orderDao = new OrderDao();
        List<Order> orders = orderDao.getAllOrders();
        orderTableModel.setOrders(orders);
    }

    
}
