/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import java.awt.event.ActionListener;

/**
 *
 * @author Limbu Mbg Sujata
 */
public class SignUp extends javax.swing.JFrame {
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

    /**
     * Creates new form signup
     */

    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        frontSignup = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        Text = new javax.swing.JLabel();
        loginlink = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1273, 789));
        setPreferredSize(new java.awt.Dimension(1273, 789));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1273, 789));
        jPanel1.setLayout(null);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.jpg"))); // NOI18N
        image.setText("jLabel1");
        jPanel1.add(image);
        image.setBounds(0, 0, 528, 789);

        usernameText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usernameText.addActionListener(this::usernameTextActionPerformed);
        jPanel1.add(usernameText);
        usernameText.setBounds(850, 170, 175, 28);

        frontSignup.setBackground(new java.awt.Color(255, 255, 255));
        frontSignup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        frontSignup.setText("Sign Up");
        jPanel1.add(frontSignup);
        frontSignup.setBounds(880, 90, 110, 30);

        emailText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailText.addActionListener(this::emailTextActionPerformed);
        jPanel1.add(emailText);
        emailText.setBounds(850, 230, 175, 30);

        signupButton.setBackground(new java.awt.Color(255, 51, 51));
        signupButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("sign up");
        jPanel1.add(signupButton);
        signupButton.setBounds(880, 350, 79, 30);

        Text.setBackground(new java.awt.Color(255, 255, 255));
        Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text.setText("Already have an account ?");
        jPanel1.add(Text);
        Text.setBounds(790, 410, 180, 17);

        loginlink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loginlink.setForeground(new java.awt.Color(51, 51, 255));
        loginlink.setText("login here.");
        loginlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlinkMouseClicked(evt);
            }
        });
        jPanel1.add(loginlink);
        loginlink.setBounds(970, 410, 80, 17);

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setText("username");
        jPanel1.add(username);
        username.setBounds(740, 170, 90, 22);

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setText("email");
        jPanel1.add(email);
        email.setBounds(770, 230, 50, 22);

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setText("password");
        jPanel1.add(password);
        password.setBounds(750, 290, 90, 22);

        passwordText.setText("jPasswordField1");
        jPanel1.add(passwordText);
        passwordText.setBounds(850, 290, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1273, 789);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void loginlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlinkMouseClicked
        // TODO add your handling code here:
        login userview = new login();
        LoginController controller = new LoginController(userview);
        controller.open();
        this.dispose();
    }//GEN-LAST:event_loginlinkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel frontSignup;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginlink;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getUsernameText(){
        return usernameText;
    }
    
    public javax.swing.JTextField getEmailText(){
        return emailText;
    }
    public javax.swing.JPasswordField getPasswordText(){
        return passwordText;
    }
    
    
    
    public void AddUserListener(ActionListener listener){
        signupButton.addActionListener(listener);
    }

}

